  name: Latest blog post workflow
  on:
    schedule:
      - cron: '0 * * * *'
    workflow_dispatch:
  jobs:
    update-readme-with-blog:
      name: Update this repo's README with latest activity
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Pull in YouTube videos
    uses: gautamkrishnar/blog-post-workflow@v1
    with:
      comment_tag_name: "YOUTUBE"
      feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UC8I3bIWugqLvi7fpVthTZ5g"
      max_post_count: 5
       template: "[![$title](https://img.youtube.com/vi/$video-id/maxresdefault.jpg)]($url)"
        - name: Pull in blog posts
          uses: gautamkrishnar/blog-post-workflow@v1
          with:
            comment_tag_name: "BLOG"
            feed_list: "https://kevinbellco.com/feed/"
            max_post_count: 5

